[tool.poetry]
packages = [{include = "tree_sitter_gosu"}]
include = [
    "tree_sitter_gosu/logging.ini",
    "CHANGELOG.md",
    "queries/*.scm",
    {path = "src/**", format = "sdist"},
    {path = "bindings/python/binding.c", format = "sdist"},
    {path = "tree_sitter_gosu/_binding*.pyd", format = "wheel"},
    {path = "tree_sitter_gosu/_binding*.so", format = "wheel"}
]

[tool.poetry.build]
script = "build.py"

[project]
name = "tree-sitter-gosu"
version = "1.0.0"
description = "A Tree-sitter grammar that parses Gosu, a statically typed, JVM-based general-purpose programming language."
readme = "README.md"
license = {file = "LICENSE"}
authors = [
    {name = "Ron Webb",email = "ron@ronella.xyz"}
]
requires-python = ">=3.14"
dependencies = [
    "logenrich (>=1.0.1,<2.0.0)",
    "env-dir-bootstrap (>=1.0.0,<2.0.0)",
    "tree-sitter (>=0.26.0,<0.27.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0", "setuptools>=84.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "black (>=26.5.1,<27.0.0)",
    "pylint (>=4.0.5,<5.0.0)",
    "pytest (>=9.0.3,<10.0.0)",
    "pytest-cov (>=7.1.0,<8.0.0)",
    "setuptools (>=84.0.0,<85.0.0)",
]
